version: "2.4"
services:
  postgres_dev:
    container_name: "corleone"
    image: "postgres:13.3-alpine"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/data/postgres
    restart: unless-stopped
volumes:
  postgres_data: